#------------------------------------------------------------------------------------------------------------
# SPDX-License-Identifier: LGPL-2.1-only
#
# Copyright (c) 2018-2020 Lawrence Livermore National Security LLC
# Copyright (c) 2018-2020 The Board of Trustees of the Leland Stanford Junior University
# Copyright (c) 2018-2020 TotalEnergies
# Copyright (c) 2019-     GEOSX Contributors
# All rights reserved
#
# See top level LICENSE, COPYRIGHT, CONTRIBUTORS, NOTICE, and ACKNOWLEDGEMENTS files for details.
#------------------------------------------------------------------------------------------------------------

# geosx@develop %clang-14
# geosx@develop %gcc-12
# geosx@develop %gcc-noAVX
#
# Uberenv command to build geos dependencies:
# python3 ./scripts/uberenv/uberenv.py --spec="+docs %clang-14"
#
# python3 ./scripts/uberenv/uberenv.py --spec="+docs %gcc-12"
#
# No AVX instructions
# python3 ./scripts/uberenv/uberenv.py --spec="+docs %gcc-noAVX"


spack:
  config:
    install_tree:
      root: $spack/..
      projections:
        all: '{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
    misc_cache: $spack/../misc_cache
    test_stage: $spack/../test_stage
    build_stage::
    - $spack/../build_stage

  # Regular TPLs do not need views
  view: false

  # Include shared variants and versions
  include:
  - ../defaults.yaml
  - ../versions.yaml

  toolchains:
    clang-14:
      - spec: '%c=llvm@14.0.6+clang~flang~lld~lldb'
        when: '%c'
      - spec: '%cxx=llvm@14.0.6+clang~flang~lld~lldb'
        when: '%cxx'
      - spec: '%fortran=gcc@12.1.1'
        when: '%fortran'
      - spec: '%mvapich2@2.3.7.clang'
        when: '%mpi'
    gcc-12:
      - spec: '%c=gcc@12.1.1'
        when: '%c'
      - spec: '%cxx=gcc@12.1.1'
        when: '%cxx'
      - spec: '%fortran=gcc@12.1.1'
        when: '%fortran'
      - spec: '%mvapich2@2.3.7.gcc'
        when: '%mpi'
    gcc-noAVX:
      - spec: cxxflags='-march=x86-64-v2 -mno-avx512f'
      - spec: '%c=gcc@12.1.1'
        when: '%c'
      - spec: '%cxx=gcc@12.1.1'
        when: '%cxx'
      - spec: '%fortran=gcc@12.1.1'
        when: '%fortran'
      - spec: '%mvapich2@2.3.7.gcc'
        when: '%mpi'

  packages:
    all:
      target: [ivybridge]
      providers:
        mpi: [mvapich2]
        blas: [intel-oneapi-mkl]
        lapack: [intel-oneapi-mkl]

    # Compilers
    llvm:
      externals:
      - spec: llvm@14.0.6+clang~flang~lld~lldb
        prefix: /usr/tce/packages/clang/clang-14.0.6-magic/
        extra_attributes:
          compilers:
            c: /usr/tce/packages/clang/clang-14.0.6-magic/bin/clang
            cxx: /usr/tce/packages/clang/clang-14.0.6-magic/bin/clang++
            fortran: /usr/tce/packages/gcc/gcc-12.1.1-magic/bin/gfortran
          environment:
            set: # Needed for scotch
              BISON: bison
              FLEX: flex
          extra_rpaths: []
    gcc:
      externals:
      - spec: gcc@12.1.1 languages:=c,c++,fortran
        prefix: /usr/tce/packages/gcc/gcc-12.1.1-magic/
        extra_attributes:
          compilers:
            c: /usr/tce/packages/gcc/gcc-12.1.1-magic/bin/gcc
            cxx: /usr/tce/packages/gcc/gcc-12.1.1-magic/bin/g++
            fortran: /usr/tce/packages/gcc/gcc-12.1.1-magic/bin/gfortran
          environment:
            set: # Needed for scotch
              BISON: bison
              FLEX: flex
          extra_rpaths: []

    # Lock down which MPI we are using
    mvapich2:
      buildable: False
      externals:
        - spec: mvapich2@2.3.7.gcc process_managers=auto %gcc@12.1.1
          prefix: /usr/tce/packages/mvapich2/mvapich2-2.3.7-gcc-12.1.1-magic
        - spec: mvapich2@2.3.7.clang process_managers=auto %clang@14.0.6
          prefix:  /usr/tce/packages/mvapich2/mvapich2-2.3.7-clang-14.0.6-magic

    intel-oneapi-mkl:
      externals:
        - spec: intel-oneapi-mkl@2022.1.0 threads=openmp
          prefix: /usr/tce/packages/mkl/mkl-2022.1.0/
      buildable: False

    # System level packages to not build
    papi:
      buildable: False
      externals:
        - spec: papi@6.0.0.1
          prefix: /usr/tce/packages/papi/papi-6.0.0.1/
    cmake:
      version: [3.26.3]
      buildable: false
      externals:
      - spec: cmake@3.26.3
        prefix: /usr/tce/packages/cmake/cmake-3.26.3
    readline:
      externals:
      - spec: readline@7.0
        prefix: /collab/usr/gapps/python/build/spack-toss3.3/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/readline-7.0-e5jqqjmcjknidgwvi353pd6umpixzxr2
      buildable: false
    m4:
      buildable: False
      externals:
        - spec: m4@1.4.18
          prefix: /usr
    perl:
      buildable: false
      externals:
      - spec: perl@5.26.3
        prefix: /usr
    pkg-config:
      buildable: false
      externals:
      - spec: pkg-config@1.8.0
        prefix: /usr
    diffutils:
      buildable: False
      externals:
        - spec: diffutils@3.3
          prefix: /usr/bin
    # This needs to be the prefix to the pygeosx LC installation
    # or system install with pygeosx dependencies
    python:
      buildable: False
      externals:
      - spec: python@3.10.8
        prefix: /usr/gapps/GEOSX/thirdPartyLibs/python/quartz-gcc-python/python/

    # This needs to be the prefix to the pygeosx LC installation
    # or system install with pygeosx dependencies
    py-sphinx:
      buildable: False
      externals:
      - spec: py-sphinx@1.6.3
        prefix: /usr/gapps/GEOSX/thirdPartyLibs/python/quartz-gcc-python/python/
    autoconf:
      buildable: False
      externals:
        - spec: autoconf@2.69
          prefix: /usr
    automake:
      buildable: False
      externals:
        - spec: automake@1.16.1
          prefix: /usr
    libtool:
      buildable: False
      externals:
        - spec: libtool@2.4.6
          prefix: /usr
    gettext:
      buildable: False
      externals:
        - spec: gettext@0.19.8.1
          prefix: /usr/bin/

    flex:
      buildable: False
      externals:
        - spec: flex@2.6.1
          prefix: /usr
