
site_name(HOST_NAME)

set(CMAKE_C_COMPILER "${CC}" CACHE PATH ""FORCE)
set(CMAKE_CXX_COMPILER "${CXX}" CACHE PATH "" FORCE)
set(ENABLE_FORTRAN OFF CACHE BOOL "" FORCE)

set(ENABLE_MPI ON CACHE PATH "" FORCE)
set(MPI_C_COMPILER "${MPICC}" CACHE PATH "" FORCE)
set(MPI_CXX_COMPILER "${MPICXX}" CACHE PATH "" FORCE)
set(MPIEXEC "mpirun" CACHE PATH "" FORCE)
