
site_name(HOST_NAME)

set(CMAKE_C_COMPILER "$ENV{CC}" CACHE PATH "" FORCE)
set(CMAKE_CXX_COMPILER "$ENV{CXX}" CACHE PATH "" FORCE)
set(CMAKE_Fortran_COMPILER "$ENV{FC}" CACHE PATH "" FORCE)
set(ENABLE_FORTRAN OFF CACHE BOOL "" FORCE)

set(ENABLE_MPI ON CACHE PATH "" FORCE)
set(MPI_C_COMPILER "$ENV{MPICC}" CACHE PATH "" FORCE)
set(MPI_CXX_COMPILER "$ENV{MPICXX}" CACHE PATH "" FORCE)
set(MPI_Fortran_COMPILER "$ENV{MPIFC}" CACHE PATH "" FORCE)
set(MPIEXEC_EXECUTABLE "$ENV{MPIEXEC}" CACHE PATH "" FORCE)

if (DEFINED $ENV{BLAS_LIBRARIES})
  set(BLAS_LIBRARIES "$ENV{BLAS_LIBRARIES}" CACHE PATH "" FORCE)
  message(STATUS "BLAS_LIBRARIES is set to ${BLAS_LIBRARIES}")
endif()

message(STATUS "LAPACK_LIBRARIES will be set to $ENV{LAPACK_LIBRARIES}")
if (DEFINED $ENV{LAPACK_LIBRARIES})
  set(LAPACK_LIBRARIES "$ENV{LAPACK_LIBRARIES}" CACHE PATH "" FORCE)
  message(STATUS "LAPACK_LIBRARIES is set to ${LAPACK_LIBRARIES}")
endif()