spack:
  config:
    install_tree:
      root: $spack/..
      projections:
        all: '{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
    misc_cache: $spack/../misc_cache
    test_stage: $spack/../test_stage
    build_stage::
    - $spack/../build_stage

  # Regular TPLs do not need views
  view: false

  # Include shared variants and versions
  include:
  - ../defaults.yaml
  - ../versions.yaml

  toolchains:
    gcc-9:
      - spec: '%c=gcc@9.4.0'
        when: '%c'
      - spec: '%cxx=gcc@9.4.0'
        when: '%cxx'
      - spec: '%fortran=gcc@9.4.0'
        when: '%fortran'
      - spec: '%openmpi@4.1.2'
        when: '%mpi'

  packages:
    all:
      target: [x86_64]

    mpi:
      require:
      - openmpi

    blas:
      require:
      - "openblas"
    lapack:
      require:
      - "openblas"

    gcc:
      externals:
      - spec: gcc@9.4.0 languages:='c,c++,fortran'
        prefix: /data_local/sw/spack/0.17.0/opt/spack/linux-rhel8-power9le/gcc-8.4.1/gcc-9.4.0-xe5cqnyajaqz75up3gflln5zlj2rue5v
        extra_attributes:
          compilers:
            c: /data_local/sw/spack/0.17.0/opt/spack/linux-rhel8-power9le/gcc-8.4.1/gcc-9.4.0-xe5cqnyajaqz75up3gflln5zlj2rue5v/bin/gcc
            cxx: /data_local/sw/spack/0.17.0/opt/spack/linux-rhel8-power9le/gcc-8.4.1/gcc-9.4.0-xe5cqnyajaqz75up3gflln5zlj2rue5v/bin/g++
            fortran: /data_local/sw/spack/0.17.0/opt/spack/linux-rhel8-power9le/gcc-8.4.1/gcc-9.4.0-xe5cqnyajaqz75up3gflln5zlj2rue5v/bin/gfortran

    autoconf:
      externals:
      - spec: autoconf@2.69
        prefix: /usr
      buildable: false
    automake:
      externals:
      - spec: automake@1.16.1
        prefix: /usr
      buildable: false
    bzip2:
      externals:
      - spec: bzip2@1.0.6
        prefix: /usr
      buildable: false
    cmake:
      externals:
      - spec: cmake@3.26.4
        prefix: /data_local/appli_local/MTS/GEOSX/cmake/3.26.4
      buildable: false
    cuda:
      externals:
      - spec: cuda@11.5.0 +allow-unsupported-compilers
        prefix: /data_local/sw/cuda/11.5.0
      buildable: false
    gettext:
      externals:
      - spec: gettext@0.19.8.1
        prefix: /usr
      buildable: false
    glibc:
      externals:
      - spec: glibc@2.28
        prefix: /usr
      buildable: false
    gmp:
      externals:
      - spec: gmp@6.1.2
        prefix: /usr
      buildable: false
    gmake:
      externals:
      - spec: gmake@4.2.1
        prefix: /usr
      buildable: false

    openblas:
      externals:
      - spec: openblas@0.3.18
        prefix: /data_local/sw/spack/0.17.0/opt/spack/linux-rhel8-power9le/gcc-9.4.0/openblas-0.3.18-vk36pzksytuhylqesg4cca7667np5sjp
      buildable: false

    libtool:
      externals:
      - spec: libtool@2.4.6
        prefix: /usr
      buildable: false
    m4:
      externals:
      - spec: m4@1.4.18
        prefix: /usr
      buildable: false

    openmpi:
      externals:
      - spec: openmpi@4.1.2 +cuda~cxx~cxx_exceptions~java+lustre~memchecker+pmi+static~wrapper-rpath schedulers=lsf %gcc@9.4.0
        prefix: /data_local/sw/openmpi/4.1.2/env/gcc-8.4.1

    # Built-in ncurses causes spack failure
    # ncurses:
    #   externals:
    #   - spec: ncurses@6.1
    #     prefix: /usr
    #   buildable: false
    perl:
      externals:
      - spec: perl@5.26.3~cpanm+opcode+open+shared+threads
        prefix: /usr
      buildable: false
    pkgconf:
      externals:
      - spec: pkgconf@1.4.2
        prefix: /usr
      buildable: false
    python:
      externals:
      - spec: python@3.8.17+bz2+crypt+ctypes+dbm+lzma+pyexpat~pythoncmd+readline+sqlite3+ssl~tkinter+uuid+zlib
        prefix: /usr
      buildable: false
    readline:
      externals:
      - spec: readline@7.0
        prefix: /usr
      buildable: false
    tar:
      externals:
      - spec: tar@1.30
        prefix: /usr
      buildable: false
    unzip:
      buildable: false
      externals:
      - spec: unzip@6.0
        prefix: /usr
    xz:
      externals:
      - spec: xz@5.2.4
        prefix: /usr
      buildable: false
    zlib:
      externals:
      - spec: zlib@1.2.11
        prefix: /usr
      buildable: false
