spack:
  config:
    install_tree:
      root: $spack/..
      projections:
        all: '{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
    misc_cache: $spack/../misc_cache
    test_stage: $spack/../test_stage
    build_stage::
    - $spack/../build_stage

  # Regular TPLs do not need views
  view: false

  compilers::
  - compiler:
      spec: gcc@=9.4.0
      paths:
        cc: /data_local/sw/spack/0.17.0/opt/spack/linux-rhel8-power9le/gcc-8.4.1/gcc-9.4.0-xe5cqnyajaqz75up3gflln5zlj2rue5v/bin/gcc
        cxx: /data_local/sw/spack/0.17.0/opt/spack/linux-rhel8-power9le/gcc-8.4.1/gcc-9.4.0-xe5cqnyajaqz75up3gflln5zlj2rue5v/bin/g++
        f77: /data_local/sw/spack/0.17.0/opt/spack/linux-rhel8-power9le/gcc-8.4.1/gcc-9.4.0-xe5cqnyajaqz75up3gflln5zlj2rue5v/bin/gfortran
        fc: /data_local/sw/spack/0.17.0/opt/spack/linux-rhel8-power9le/gcc-8.4.1/gcc-9.4.0-xe5cqnyajaqz75up3gflln5zlj2rue5v/bin/gfortran
      flags: {}
      operating_system: almalinux8
      target: ppc64le
      modules: []
      environment:
        set: # Needed for scotch
          BISON: bison
          FLEX: flex
        prepend_path:
          LD_LIBRARY_PATH: /data_local/sw/lsf/10.1/linux3.10-glibc2.17-ppc64le/lib
      extra_rpaths: []

  packages:
    all:
      target: [x86_64]
      compiler: [gcc]
      providers:
        blas: [openblas]
        lapack: [openblas]
        mpi: [openmpi]


    # v0.6.2
    blt:
      require: "@git.9ff77344f0b2a6ee345e452bddd6bfd46cbbfa35=develop"

    hypre:
      require: "@git.74b8a409407637b19103fa2170c54a280c03d43f"

    # v2024.07.0
    chai:
      require: "@git.df7741f1dbbdc5fff5f7d626151fdf1904e62b19=develop"

    # v2024.07.0
    umpire:
      require: "@git.abd729f40064175e999a83d11d6b073dac4c01d2=develop"

    # v2024.07.0
    raja:
      require: "@git.4d7fcba55ebc7cb972b7cc9f6778b48e43792ea1=develop"

    # v2024.07.0
    camp:
      require: "@git.0f07de4240c42e0b38a8d872a20440cb4b33d9f5=main"

    # v2.12.0
    caliper:
      require: "@git.287b7f3ad2d12f520aad04268d44f353cd05403c"

    # v0.9.2
    conduit:
      require: "@git.ad86e316ad56a75c099d30ca5ce75cff275b5924=develop"

    uncrustify:
      require: "@git.401a4098bce9dcc47e024987403f2d59d9ba7bd2"

    superlu-dist:
      require: "@git.0f6efc377df2440c235452d13d28d2c717f832a1"

    autoconf:
      externals:
      - spec: autoconf@2.69
        prefix: /usr
      buildable: false
    automake:
      externals:
      - spec: automake@1.16.1
        prefix: /usr
      buildable: false
    bison:
      externals:
      - spec: bison@3.0.4
        prefix: /usr
      buildable: false
    bzip2:
      externals:
      - spec: bzip2@1.0.6
        prefix: /usr
      buildable: false
    cmake:
      externals:
      - spec: cmake@3.26.4
        prefix: /data_local/appli_local/MTS/GEOSX/cmake/3.26.4
      buildable: false
    cuda:
      externals:
      - spec: cuda@11.5.0 +allow-unsupported-compilers
        prefix: /data_local/sw/cuda/11.5.0
      buildable: false
    flex:
      externals:
      - spec: flex@2.6.1+lex
        prefix: /usr
      buildable: false
    gettext:
      externals:
      - spec: gettext@0.19.8.1
        prefix: /usr
      buildable: false
    glibc:
      externals:
      - spec: glibc@2.28
        prefix: /usr
      buildable: false
    gmp:
      externals:
      - spec: gmp@6.1.2
        prefix: /usr
      buildable: false
    gmake:
      externals:
      - spec: gmake@4.2.1
        prefix: /usr
      buildable: false

    openblas:
      externals:
      - spec: openblas@0.3.18
        prefix: /data_local/sw/spack/0.17.0/opt/spack/linux-rhel8-power9le/gcc-9.4.0/openblas-0.3.18-vk36pzksytuhylqesg4cca7667np5sjp
      buildable: false
    blas:
      buildable: false
    lapack:
      buildable: false

    libtool:
      externals:
      - spec: libtool@2.4.6
        prefix: /usr
      buildable: false
    m4:
      externals:
      - spec: m4@1.4.18
        prefix: /usr
      buildable: false

    # Spack may grab for mpi & we don't want to use them
    mpi:
      buildable: false

    openmpi:
      externals:
      - spec: openmpi@4.1.2%gcc@9.4.0 +cuda~cxx~cxx_exceptions~java+lustre~memchecker+pmi+static~wrapper-rpath schedulers=lsf
        prefix: /data_local/sw/openmpi/4.1.2/env/gcc-8.4.1

    # Built-in ncurses causes spack failure
    # ncurses:
    #   externals:
    #   - spec: ncurses@6.1
    #     prefix: /usr
    #   buildable: false
    perl:
      externals:
      - spec: perl@5.26.3~cpanm+opcode+open+shared+threads
        prefix: /usr
      buildable: false
    pkgconf:
      externals:
      - spec: pkgconf@1.4.2
        prefix: /usr
      buildable: false
    python:
      externals:
      - spec: python@3.8.17+bz2+crypt+ctypes+dbm+lzma+nis+pyexpat~pythoncmd+readline+sqlite3+ssl~tkinter+uuid+zlib
        prefix: /usr
      buildable: false
    readline:
      externals:
      - spec: readline@7.0
        prefix: /usr
      buildable: false
    tar:
      externals:
      - spec: tar@1.30
        prefix: /usr
      buildable: false
    unzip:
      buildable: false
      externals:
      - spec: unzip@6.0
        prefix: /usr
    xz:
      externals:
      - spec: xz@5.2.4
        prefix: /usr
      buildable: false
    zlib:
      externals:
      - spec: zlib@1.2.11
        prefix: /usr
      buildable: false
