spack:
  config:
    install_tree:
      root: $spack/..
      projections:
        all: '{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
    misc_cache: $spack/../misc_cache
    test_stage: $spack/../test_stage
    build_stage::
    - $spack/../build_stage

  # Regular TPLs do not need views
  view: false

  compilers::
  # Pecan CPU/GPU compiler
  - compiler:
      environment:
        set: # Needed for scotch
          BISON: bison
          FLEX: flex
      extra_rpaths: []
      flags:
        cflags: -pthread
        cxxflags: -pthread
      modules: []
      operating_system: centos7
      paths:
        cc: /apps/gcc/8.2.0/x86_64/bin/gcc
        cxx: /apps/gcc/8.2.0/x86_64/bin/g++
        f77: /apps/gcc/8.2.0/x86_64/bin/gfortran
        fc: /apps/gcc/8.2.0/x86_64/bin/gfortran
      spec: gcc@8.2.0
      target: x86_64

  packages:
    all:
      target: [x86_64]
      compiler: [gcc, clang]
      providers:
        blas: [intel-mkl]
        lapack: [intel-mkl]
        mpi: [openmpi]


    # v0.6.2
    blt:
      require: "@git.9ff77344f0b2a6ee345e452bddd6bfd46cbbfa35=develop"

    hypre:
      require: "@git.21e5953ddc6daaa24699236108866afa597a415c"

    # v2024.07.0
    chai:
      require: "@git.df7741f1dbbdc5fff5f7d626151fdf1904e62b19=develop"

    # v2024.07.0
    umpire:
      require: "@git.abd729f40064175e999a83d11d6b073dac4c01d2=develop"

    # v2024.07.0
    raja:
      require: "@git.4d7fcba55ebc7cb972b7cc9f6778b48e43792ea1=develop"

    # v2024.07.0
    camp:
      require: "@git.0f07de4240c42e0b38a8d872a20440cb4b33d9f5=main"

    # v2.12.0
    caliper:
      require: "@git.287b7f3ad2d12f520aad04268d44f353cd05403c"

    # v0.9.2
    conduit:
      require: "@git.ad86e316ad56a75c099d30ca5ce75cff275b5924=develop"

    uncrustify:
      require: "@git.401a4098bce9dcc47e024987403f2d59d9ba7bd2"

    superlu-dist:
      require: "@git.0f6efc377df2440c235452d13d28d2c717f832a1"

    autoconf:
      version: [2.71]
      buildable: false
      externals:
      - spec: autoconf@2.71
        prefix: /usr
    automake:
      version: [1.16.5]
      buildable: false
      externals:
      - spec: automake@1.16.5
        prefix: /usr
    bison:
      version: [3.8.2]
      buildable: false
      externals:
      - spec: bison@3.8.2
        prefix: /usr
    cmake:
      version: [3.28.3]
      buildable: false
      externals:
      - spec: cmake@3.28.3
        prefix: /usr/local
    cuda:
      buildable: False
      externals:
      - spec: cuda@11.5.1 +allow-unsupported-compilers
        prefix: /hrtc/apps/cuda/11.5.119/x86_64/centos7
    flex:
      version: [2.6.4]
      buildable: false
      externals:
      - spec: flex@2.6.4
        prefix: /usr

    # Lock down blas, lapack implementation
    intel-mkl:
      buildable: False
      externals:
        # Pecan CPU/GPU
        - spec: intel-mkl@2019.5.281%gcc@8.2.0 threads=openmp
          prefix: /opt/intel/compilers_and_libraries_2019.5.281/linux/mkl/
    blas:
      buildable: false

    lapack:
      buildable: false

    m4:
      buildable: false
      externals:
      - spec: m4@1.4.18
        prefix: /usr

    # Spack may grab for mpi & we don't want to use them
    mpi:
      buildable: false

    openmpi:
      externals:
      # Pecan CPU/GPU
      - spec: openmpi@4.0.1%gcc@8.2.0
        prefix: /hrtc/apps/mpi/openmpi/4.0.1/RDHPC/gcc/8.2.0
    perl:
      buildable: false
      externals:
      - spec: perl@5.34.0
        prefix: /usr
    pkg-config:
      buildable: false
      externals:
      - spec: pkg-config@0.29.2
        prefix: /usr
    py-sphinx:
      buildable: false
      externals:
      - spec: py-sphinx@4.3.2
        prefix: /usr
    python:
      buildable: false
      externals:
      - spec: python@3.10.12
        prefix: /usr
    tar:
      buildable: false
      externals:
      - spec: tar@1.34
        prefix: /usr
    unzip:
      buildable: false
      externals:
      - spec: unzip@6.0
        prefix: /usr
    xz:
      buildable: false
      externals:
      - spec: xz@5.2.5
        prefix: /usr
