spack:
  config:
    install_tree:
      root: $spack/..
      projections:
        all: '{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
    misc_cache: $spack/../misc_cache
    test_stage: $spack/../test_stage
    build_stage::
    - $spack/../build_stage

  view: false

  include:
  - ../defaults.yaml
  - ../versions.yaml

  compilers::
  - compiler:
      spec: clang@20
      operating_system: ubuntu22.04
      target: x86_64
      paths:
        cc: /usr/bin/clang-20
        cxx: /usr/bin/clang++-20
        f77: /usr/bin/gfortran-12
        fc: /usr/bin/gfortran-12
      flags:
        cflags: -pthread
        cxxflags: -pthread
      modules: []
      extra_rpaths: []

  packages:
    all:
      target: [x86_64]
      compiler: [clang]
      providers:
        blas: [netlib-lapack]
        lapack: [netlib-lapack]
        mpi: [openmpi]

    cmake:
      version: [3.28.6]
      buildable: false
      externals:
      - spec: cmake@3.28.6
        prefix: /usr/local

    hip:
      buildable: false
      externals:
      - spec: hip@6.4.2
        prefix: /opt/rocm-6.4.2

    rocprim:
      buildable: false
      externals:
      - spec: rocprim@6.4.2
        prefix: /opt/rocm-6.4.2

    rocsparse:
      buildable: false
      externals:
      - spec: rocsparse@6.4.2
        prefix: /opt/rocm-6.4.2

    roctracer:
      buildable: false
      externals:
      - spec: roctracer@6.4.2
        prefix: /opt/rocm-6.4.2

    rocblas:
      buildable: false
      externals:
      - spec: rocblas@6.4.2
        prefix: /opt/rocm-6.4.2

    rocrand:
      buildable: false
      externals:
      - spec: rocrand@6.4.2
        prefix: /opt/rocm-6.4.2

    rocsolver:
      buildable: false
      externals:
      - spec: rocsolver@6.4.2
        prefix: /opt/rocm-6.4.2

    rocthrust:
      buildable: false
      externals:
      - spec: rocthrust@6.4.2
        prefix: /opt/rocm-6.4.2

    hipblas:
      buildable: false
      externals:
      - spec: hipblas@6.4.2 +rocm
        prefix: /opt/rocm-6.4.2

    hipsparse:
      buildable: false
      externals:
      - spec: hipsparse@6.4.2 +rocm
        prefix: /opt/rocm-6.4.2

    hipfft:
      buildable: false
      externals:
      - spec: hipfft@6.4.2 +rocm
        prefix: /opt/rocm-6.4.2

    hipsolver:
      buildable: false
      externals:
      - spec: hipsolver@6.4.2 +rocm
        prefix: /opt/rocm-6.4.2

    hiprand:
      buildable: false
      externals:
      - spec: hiprand@6.4.2 +rocm
        prefix: /opt/rocm-6.4.2

    rocm-device-libs:
      buildable: false
      externals:
      - spec: rocm-device-libs@6.4.2
        prefix: /opt/rocm-6.4.2

    hsa-rocr-dev:
      buildable: false
      externals:
      - spec: hsa-rocr-dev@6.4.2
        prefix: /opt/rocm-6.4.2

    openmpi:
      externals:
      - spec: openmpi@4.1.2%clang
        prefix: /usr

    # External packages
    autoconf:
      version: [2.71]
      buildable: false
      externals:
      - spec: autoconf@2.71
        prefix: /usr
    automake:
      version: [1.16.5]
      buildable: false
      externals:
      - spec: automake@1.16.5
        prefix: /usr
    findutils:
      version: [4.7.0]
      buildable: false
      externals:
      - spec: findutils@4.7.0
        prefix: /usr
    m4:
      buildable: false
      externals:
      - spec: m4@1.4.18
        prefix: /usr
    mpfr:
      buildable: false
      externals:
      - spec: mpfr@6.0.2
        prefix: /usr
    perl:
      buildable: false
      externals:
      - spec: perl@5.34.0
        prefix: /usr
    pkg-config:
      buildable: false
      externals:
      - spec: pkg-config@0.29.2
        prefix: /usr
    py-sphinx:
      buildable: false
      externals:
      - spec: py-sphinx@4.3.2
        prefix: /usr
    python:
      buildable: false
      externals:
      - spec: python@3.10.12
        prefix: /usr
    readline:
      buildable: false
      externals:
      - spec: readline@8.0
        prefix: /usr
    tar:
      buildable: false
      externals:
      - spec: tar@1.34
        prefix: /usr
    unzip:
      buildable: false
      externals:
      - spec: unzip@6.0
        prefix: /usr
    xz:
      buildable: false
      externals:
      - spec: xz@5.2.5
        prefix: /usr
    zlib:
      buildable: false
      externals:
      - spec: zlib@1.2.11
        prefix: /usr