spack:
  config:
    install_tree:
      root: $spack/..
      projections:
        all: '{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
    misc_cache: $spack/../misc_cache
    test_stage: $spack/../test_stage
    build_stage::
    - $spack/../build_stage

  # Regular TPLs do not need views
  view: false

  compilers::
  # Sherlock CPU/GPU Compiler
  - compiler:
      environment: {}
      extra_rpaths: []
      flags:
        cflags: -pthread
        cxxflags: -pthread
      modules: []
      operating_system: centos7
      paths:
        cc: /share/software/user/open/gcc/10.1.0/bin/gcc
        cxx: /share/software/user/open/gcc/10.1.0/bin/g++
        f77: /share/software/user/open/gcc/10.1.0/bin/gfortran
        fc: /share/software/user/open/gcc/10.1.0/bin/gfortran
      spec: gcc@10.1.0
      target: x86_64

  packages:
    all:
      target: [x86_64]
      compiler: [gcc, clang]
      providers:
        blas: [openblas]
        lapack: [openblas]
        mpi: [openmpi]


    # v0.6.2
    blt:
      require: "@git.9ff77344f0b2a6ee345e452bddd6bfd46cbbfa35=develop"

    # Develop - 7/31/24
    hypre:
      require: "@git.06da35b1a4b1066a093bc0c6c48aee12bee74cd4"

    # v2024.0.2.2
    chai:
      require: "@git.5ba0944d862513f600432c34b009824875df27e5=develop"

    # v2024.02.1
    umpire:
      require: "@git.3058d562fc707650e904f9321b1ee9bcebad3ae2=develop"

    # v2024.02.2
    raja:
      require: "@git.593f756b14ac57ded33ee61d8d2292d4beb840e6=develop"

    # v2024.02.1
    camp:
      require: "@git.79c320fa09db987923b56884afdc9f82f4b70fc4=main"

    # v0.9.2
    conduit:
      require: "@git.ad86e316ad56a75c099d30ca5ce75cff275b5924=develop"

    uncrustify:
      require: "@git.401a4098bce9dcc47e024987403f2d59d9ba7bd2"

    superlu-dist:
      require: "@git.0f6efc377df2440c235452d13d28d2c717f832a1"

    autoconf:
      version: [2.71]
      buildable: false
      externals:
      - spec: autoconf@2.71
        prefix: /usr
    automake:
      version: [1.16.5]
      buildable: false
      externals:
      - spec: automake@1.16.5
        prefix: /usr
    bison:
      version: [3.8.2]
      buildable: false
      externals:
      - spec: bison@3.8.2
        prefix: /usr
    cmake:
      version: [3.28.3]
      buildable: false
      externals:
      - spec: cmake@3.28.3
        prefix: /usr/local
    cuda:
      buildable: False
      externals:
      - spec: cuda@11.7.1 +allow-unsupported-compilers
        prefix: /share/software/user/open/cuda/11.7.1/
    flex:
      version: [2.6.4]
      buildable: false
      externals:
      - spec: flex@2.6.4
        prefix: /usr

    # Lock down blas, lapack implementation
    intel-mkl:
      buildable: False

    openblas:
      buildable: false
      externals:
      - spec: openblas@0.3.10
        prefix: /share/software/user/open/openblas/0.3.10/

    blas:
      buildable: false

    lapack:
      buildable: false

    m4:
      buildable: false
      externals:
      - spec: m4@1.4.18
        prefix: /usr

    # Spack may grab for mpi & we don't want to use them
    mpi:
      buildable: false

    openmpi:
      externals:
      # Sherlock CPU/GPU
      - spec: openmpi@4.1.2%gcc@10.1.0
        prefix: /share/software/user/open/openmpi/4.1.2
    perl:
      buildable: false
      externals:
      - spec: perl@5.34.0
        prefix: /usr
    pkg-config:
      buildable: false
      externals:
      - spec: pkg-config@0.29.2
        prefix: /usr
    py-sphinx:
      buildable: false
      externals:
      - spec: py-sphinx@4.3.2
        prefix: /usr
    python:
      buildable: false
      externals:
      - spec: python@3.10.12
        prefix: /usr
    tar:
      buildable: false
      externals:
      - spec: tar@1.34
        prefix: /usr
    unzip:
      buildable: false
      externals:
      - spec: unzip@6.0
        prefix: /usr
    xz:
      buildable: false
      externals:
      - spec: xz@5.2.5
        prefix: /usr
