# Specify build_language to bypass ascii codec decode error
spack:
  config:
    install_tree:
      root: $spack/..
      projections:
        all: '{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
    misc_cache: $spack/../misc_cache
    test_stage: $spack/../test_stage
    build_stage::
    - $spack/../build_stage

  # Regular TPLs do not need views
  view: false

  # Include shared variants and versions
  include:
  - ../defaults.yaml
  - ../versions.yaml

  packages:
    all:
      target: [x86_64]
      providers:
        mpi: [openmpi]
        blas: [openblas]
        lapack: [openblas]

    gcc:
      externals:
      - spec: gcc@10.5.0 languages:='c,c++,fortran'
        prefix: /share/software/user/open/gcc/10.1.0
        extra_attributes:
          compilers:
            c: /share/software/user/open/gcc/10.1.0/bin/gcc
            cxx: /share/software/user/open/gcc/10.1.0/bin/g++
            fortran: /share/software/user/open/gcc/10.1.0/bin/gfortran

    autoconf:
      buildable: false
      externals:
      - spec: autoconf@2.69
        prefix: /usr

    automake:
      buildable: false
      externals:
      - spec: automake@1.13.4
        prefix: /usr

    cmake:
      buildable: false
      externals:
      - spec: cmake@3.31.4
        prefix: /share/software/user/open/cmake/3.31.4

    cuda:
      buildable: false
      externals:
      - spec: cuda@12.4.0 +allow-unsupported-compilers
        prefix: /share/software/user/open/cuda/12.4.0/

    #diffutils:
    #  buildable: false
    #  externals:
    #  - spec: diffutils@3.3
    #    prefix: /usr

    #gettext:
    #  buildable: false
    #  externals:
    #  - spec: gettext@0.19.8.1
    #    prefix: /usr

    #libtool:
    #  buildable: false
    #  externals:
    #  - spec: libtool@2.4.2
    #    prefix: /usr

    openblas:
      buildable: false
      externals:
      - spec: openblas@0.3.10
        prefix: /share/software/user/open/openblas/0.3.10

    blas:
      buildable: false

    lapack:
      buildable: false

    m4:
      buildable: false
      externals:
      - spec: m4@1.4.16
        prefix: /usr

    # Spack may grab for mpi & we don't want to use them
    mpi:
      buildable: false

    openmpi:
      buildable: false
      externals:
      - spec: openmpi@4.1.2
        prefix: /share/software/user/open/openmpi/4.1.2

    perl:
      buildable: false
      externals:
      - spec: perl@5.16.3
        prefix: /usr

    pkg-config:
      buildable: false
      externals:
      - spec: pkg-config@0.27.1
        prefix: /usr

    python:
      buildable: false
      externals:
      - spec: python@3.6.8
        prefix: /oak/stanford/groups/tchelepi/geos-sherlock/pythonVenv/geosxEnv

    tar:
      buildable: false
      externals:
      - spec: tar@1.26
        prefix: /usr

    unzip:
      buildable: false
      externals:
      - spec: unzip@6.0
        prefix: /usr

    xz:
      buildable: false
      externals:
      - spec: xz@5.2.2
        prefix: /usr
