spack:
  config:
    install_tree:
      root: $spack/..
      projections:
        all: '{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
    misc_cache: $spack/../misc_cache
    test_stage: $spack/../test_stage
    build_stage::
    - $spack/../build_stage

  # Regular TPLs do not need views
  view: false

  compilers::
  # Sherlock CPU/GPU Compiler
  - compiler:
      environment: {}
      extra_rpaths: []
      flags:
        cflags: -pthread
        cxxflags: -pthread
      modules: []
      operating_system: centos7
      paths:
        cc: /share/software/user/open/gcc/10.1.0/bin/gcc
        cxx: /share/software/user/open/gcc/10.1.0/bin/g++
        f77: /share/software/user/open/gcc/10.1.0/bin/gfortran
        fc: /share/software/user/open/gcc/10.1.0/bin/gfortran
      spec: gcc@10.1.0
      target: x86_64

  packages:
    all:
      target: [x86_64]
      compiler: [gcc, clang]
      providers:
        blas: [openblas]
        lapack: [openblas]
        mpi: [openmpi]


    blt:
      require: "@git.5a792c1775e7a7628d84dcde31652a689f1df7b5=develop"

    hypre:
      require: "@git.d475cdfc63ac59ea9a554493a06e4033b8d6fade"

    chai:
      require: "@git.6fe3470ad020303530af2f3dbbfe18826bd3319b=develop"

    umpire:
      require: "@git.4bd9b2ded81d3216b3f62e2aad62d0e34fe2c256=develop"

    raja:
      require: "@git.e330b2560747d5417cd7bd265fab3fb91d32ecbd=develop"

    camp:
      require: "@git.ac34c25b722a06b138bc045d38bfa5e8fa3ec9c5=main"

    uncrustify:
      require: "@git.401a4098bce9dcc47e024987403f2d59d9ba7bd2"

    superlu-dist:
      require: "@git.0f6efc377df2440c235452d13d28d2c717f832a1"

    autoconf:
      version: [2.71]
      buildable: false
      externals:
      - spec: autoconf@2.71
        prefix: /usr
    automake:
      version: [1.16.5]
      buildable: false
      externals:
      - spec: automake@1.16.5
        prefix: /usr
    bison:
      version: [3.8.2]
      buildable: false
      externals:
      - spec: bison@3.8.2
        prefix: /usr
    cmake:
      version: [3.28.3]
      buildable: false
      externals:
      - spec: cmake@3.28.3
        prefix: /usr/local
    cuda:
      buildable: False
      externals:
      - spec: cuda@11.7.1 +allow-unsupported-compilers
        prefix: /share/software/user/open/cuda/11.7.1/
    flex:
      version: [2.6.4]
      buildable: false
      externals:
      - spec: flex@2.6.4
        prefix: /usr

    # Lock down blas, lapack implementation
    intel-mkl:
      buildable: False

    openblas:
      buildable: false
      externals:
      - spec: openblas@0.3.10
        prefix: /share/software/user/open/openblas/0.3.10/

    blas:
      buildable: false

    lapack:
      buildable: false

    m4:
      buildable: false
      externals:
      - spec: m4@1.4.18
        prefix: /usr

    # Spack may grab for mpi & we don't want to use them
    mpi:
      buildable: false

    openmpi:
      externals:
      # Sherlock CPU/GPU
      - spec: openmpi@4.1.2%gcc@10.1.0
        prefix: /share/software/user/open/openmpi/4.1.2
    perl:
      buildable: false
      externals:
      - spec: perl@5.34.0
        prefix: /usr
    pkg-config:
      buildable: false
      externals:
      - spec: pkg-config@0.29.2
        prefix: /usr
    py-sphinx:
      buildable: false
      externals:
      - spec: py-sphinx@4.3.2
        prefix: /usr
    python:
      buildable: false
      externals:
      - spec: python@3.10.12
        prefix: /usr
    tar:
      buildable: false
      externals:
      - spec: tar@1.34
        prefix: /usr
    unzip:
      buildable: false
      externals:
      - spec: unzip@6.0
        prefix: /usr
    xz:
      buildable: false
      externals:
      - spec: xz@5.2.5
        prefix: /usr
