# Specify build_language to bypass ascii codec decode error
spack:
  config:
    install_tree:
      root: $spack/..
      projections:
        all: '{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
    misc_cache: $spack/../misc_cache
    test_stage: $spack/../test_stage
    build_stage:
    - $spack/../build_stage

  # Regular TPLs do not need views
  view: false

  compilers::
  # Sherlock CPU/GPU Compiler (centos7 x86_64)
  - compiler:
      spec: gcc@10.1.0
      operating_system: centos7
      target: x86_64
      paths:
        cc: /share/software/user/open/gcc/10.1.0/bin/gcc
        cxx: /share/software/user/open/gcc/10.1.0/bin/g++
        f77: /share/software/user/open/gcc/10.1.0/bin/gfortran
        fc: /share/software/user/open/gcc/10.1.0/bin/gfortran
      flags:
        cflags: -pthread
        cxxflags: -pthread
      modules: []
      environment:
        set: # Needed for scotch
          BISON: bison
          FLEX: flex
      extra_rpaths: []

  packages:
    all:
      target: [x86_64]
      compiler: [gcc]
      providers:
        mpi: [openmpi]
        blas: [openblas]
        lapack: [openblas]

    # v0.6.2
    blt:
      require: "@git.9ff77344f0b2a6ee345e452bddd6bfd46cbbfa35=develop"

    # master - 10/18/24
    hypre:
      require: "@git.c893886d15eb57e87dd36efec23693ece3ddc88e"

    # v2024.07.0
    chai:
      require: "@git.df7741f1dbbdc5fff5f7d626151fdf1904e62b19=develop"

    # v2024.07.0
    umpire:
      require: "@git.abd729f40064175e999a83d11d6b073dac4c01d2=develop"

    # v2024.07.0
    raja:
      require: "@git.4d7fcba55ebc7cb972b7cc9f6778b48e43792ea1=develop"

    # v2024.07.0
    camp:
      require: "@git.0f07de4240c42e0b38a8d872a20440cb4b33d9f5=main"

    # v2.12.0
    caliper:
      require: "@git.287b7f3ad2d12f520aad04268d44f353cd05403c"

    # v0.9.2
    conduit:
      require: "@git.ad86e316ad56a75c099d30ca5ce75cff275b5924=develop"

    uncrustify:
      require: "@git.401a4098bce9dcc47e024987403f2d59d9ba7bd2"

    superlu-dist:
      require: "@git.0f6efc377df2440c235452d13d28d2c717f832a1"

    autoconf:
      buildable: False
      externals:
        - spec: autoconf@2.69
          prefix: /usr

    automake:
      buildable: False
      externals:
        - spec: automake@1.13.4
          prefix: /usr

    bison:
      version: [3.0.4]
      buildable: false
      externals:
      - spec: bison@3.0.4
        prefix: /usr

    cmake:
      buildable: false
      externals:
        - spec: cmake@3.31.4
          prefix: /share/software/user/open/cmake/3.31.4

    cuda:
      buildable: False
      externals:
      - spec: cuda@12.4.0 +allow-unsupported-compilers
        prefix: /share/software/user/open/cuda/12.4.0/

    diffutils:
      buildable: False
      externals:
        - spec: diffutils@3.3
          prefix: /usr

    flex:
      buildable: False
      externals:
        - spec: flex@2.5.37
          prefix: /usr

    gettext:
      buildable: False
      externals:
        - spec: gettext@0.19.8.1
          prefix: /usr

    libtool:
      buildable: False
      externals:
        - spec: libtool@2.4.2
          prefix: /usr

    openblas:
      buildable: False
      externals:
        - spec: openblas@0.3.10 
          prefix: /share/software/user/open/openblas/0.3.10

    blas:
      buildable: false

    lapack:
      buildable: false

    m4:
      buildable: False
      externals:
        - spec: m4@1.4.16
          prefix: /usr

    # Spack may grab for mpi & we don't want to use them
    mpi:
      buildable: false

    openmpi:
      buildable: False
      externals:
        - spec: openmpi@4.1.2
          prefix: /share/software/user/open/openmpi/4.1.2

    perl:
      buildable: false
      externals:
      - spec: perl@5.16.3
        prefix: /usr

    pkg-config:
      buildable: false
      externals:
      - spec: pkg-config@0.27.1
        prefix: /usr

    python:
      buildable: False
      externals:
      - spec: python@3.6.8
        prefix: /oak/stanford/groups/tchelepi/geos-sherlock/pythonVenv/geosxEnv

    tar:
      buildable: false
      externals:
      - spec: tar@1.26
        prefix: /usr

    unzip:
      buildable: false
      externals:
      - spec: unzip@6.0
        prefix: /usr

    xz:
      buildable: false
      externals:
      - spec: xz@5.2.2
        prefix: /usr
