spack:
  config:
    install_tree:
      root: $spack/..
      projections:
        all: '{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
    misc_cache: $spack/../misc_cache
    test_stage: $spack/../test_stage
    build_stage::
    - $spack/../build_stage

  # Regular TPLs do not need views
  view: false

  # Include shared variants and versions
  include:
  - ../defaults.yaml
  - ../versions.yaml

  packages:
    all:
      target: [x86_64]
      providers:
        blas: [netlib-lapack]
        lapack: [netlib-lapack]
        mpi: [openmpi]

    gcc:
      externals:
      - spec: gcc@9.4.0 languages:='c,c++,fortran'
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/gcc-9
            cxx: /usr/bin/g++-9
            fortran: /usr/bin/gfortran-9
      - spec: gcc@10.5.0 languages:='c,c++,fortran'
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/gcc-10
            cxx: /usr/bin/g++-10
            fortran: /usr/bin/gfortran-10
      - spec: gcc@11.4.0 languages:='c,c++,fortran'
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/gcc-11
            cxx: /usr/bin/g++-11
            fortran: /usr/bin/gfortran-11
      - spec: gcc@12.3.0 languages:='c,c++,fortran'
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/gcc-12
            cxx: /usr/bin/g++-12
            fortran: /usr/bin/gfortran-12
      - spec: gcc@13.3.0 languages:='c,c++,fortran'
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/gcc-13
            cxx: /usr/bin/g++-13
            fortran: /usr/bin/gfortran-13
    clang:
      version: [10.0.0, 15.0.7]
      buildable: false
      externals:
      - spec: clang@10.0.0 languages:='c,c++'
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/clang-10
            cxx: /usr/bin/clang++-10
      - spec: clang@15.0.7 languages:='c,c++'
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/clang-15
            cxx: /usr/bin/clang++-15

    autoconf:
      version: [2.71]
      buildable: false
      externals:
      - spec: autoconf@2.71
        prefix: /usr
    automake:
      version: [1.16.5]
      buildable: false
      externals:
      - spec: automake@1.16.5
        prefix: /usr
    cmake:
      version: [3.28.3]
      buildable: false
      externals:
      - spec: cmake@3.28.3
        prefix: /usr/local
    cuda:
      buildable: False
      externals:
      - spec: cuda@11.8.0 +allow-unsupported-compilers
        prefix: /usr/local/cuda
    findutils:
      version: [4.7.0]
      buildable: false
      externals:
      - spec: findutils@4.7.0
        prefix: /usr
    m4:
      buildable: false
      externals:
      - spec: m4@1.4.18
        prefix: /usr
    mpfr:
      buildable: false
      externals:
      - spec: mpfr@6.0.2
        prefix: /usr

    # Spack may grab for mpi & we don't want to use them
    mpi:
      buildable: false

    netlib-lapack:
      buildable: false
      externals:
      - spec: netlib-lapack@3.10.0
        prefix: /usr
    netlib-blas:
      buildable: false
      externals:
      - spec: netlib-blas@3.10.0
        prefix: /usr
    openmpi:
      externals:
      - spec: openmpi@4.1.2%clang
        prefix: /usr
      - spec: openmpi@1.10.7%gcc@8
        prefix: /usr/lib64/openmpi
        modules: [mpi]
      - spec: openmpi@4.1.2%gcc@9
        prefix: /usr
      - spec: openmpi@4.1.2%gcc@10
        prefix: /usr
      - spec: openmpi@4.1.2%gcc@11
        prefix: /usr
      - spec: openmpi@4.1.2%gcc@12
        prefix: /usr
    hwloc:
      buildable: false
      externals:
      - spec: hwloc@2.7.0
        prefix: /usr
    perl:
      buildable: false
      externals:
      - spec: perl@5.34.0
        prefix: /usr
    pkg-config:
      buildable: false
      externals:
      - spec: pkg-config@0.29.2
        prefix: /usr
    py-sphinx:
      buildable: false
      externals:
      - spec: py-sphinx@4.3.2
        prefix: /usr
    python:
      buildable: false
      externals:
      - spec: python@3.10.12
        prefix: /usr
    readline:
      buildable: false
      externals:
      - spec: readline@8.0
        prefix: /usr
    tar:
      buildable: false
      externals:
      - spec: tar@1.34
        prefix: /usr
    unzip:
      buildable: false
      externals:
      - spec: unzip@6.0
        prefix: /usr
    xz:
      buildable: false
      externals:
      - spec: xz@5.2.5
        prefix: /usr
    zlib:
      buildable: false
      externals:
      - spec: zlib@1.2.11
        prefix: /usr
    doxygen:
      buildable: false
      externals:
      - spec: doxygen@1.9.1
        prefix: /usr
    bison:
      buildable: false
      externals:
      - spec: bison@3.8.2
        prefix: /usr
    flex:
      buildable: false
      externals:
      - spec: flex@2.6.4
        prefix: /usr
