# This is a Spack Environment file for Pangea-4 docker image.
# - replicate Pangea-4 environement as close as possible
#   while targeting x86_64 for ci/cd.
# - used with onetechssc/pangea4:gcc12.1-hpcxompi2.20.0-onemkl2023.2.0_v1.0
#   docker image
#
# It describes a set of packages to be installed, along with
# configuration settings.
#
# Run command from the top-level of the repository:
# ./scripts/uberenv/uberenv.py                                         \
#    --spec "%gcc@12.2.1 ~openmp~pygeosx"                              \
#    --spack-env-file=docker/TotalEnergies/pangea-4/pangea4-spack.yaml \
#    --project-json=.uberenv_config.json                               \
#    --prefix ${GEOS_TPL_DIR}
spack:
  config:
    # make sure you survive our wonderfull proxy when testing on prem
    connect_timeout: 120
    url_fetch_method: curl
    install_tree:
      root: $spack/..
      projections:
        all: '{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
    misc_cache: $spack/../misc_cache
    test_stage: $spack/../test_stage
    build_stage::
    - $spack/../build_stage

  # Regular TPLs do not need views
  view: false

  #############
  # COMPILERS #
  #############

  compilers:
  - compiler:
      spec: gcc@=12.2.1
      paths:
        cc: /opt/spack/opt/spack/linux-centos8-zen/gcc-8.5.0/gcc-12.1.0-74x6yognzvkzjoh6zvmkimhhsuijh237/bin/gcc
        cxx: /opt/spack/opt/spack/linux-centos8-zen/gcc-8.5.0/gcc-12.1.0-74x6yognzvkzjoh6zvmkimhhsuijh237/bin/g++
        f77: /opt/spack/opt/spack/linux-centos8-zen/gcc-8.5.0/gcc-12.1.0-74x6yognzvkzjoh6zvmkimhhsuijh237/bin/gfortran
        fc: /opt/spack/opt/spack/linux-centos8-zen/gcc-8.5.0/gcc-12.1.0-74x6yognzvkzjoh6zvmkimhhsuijh237/bin/gfortran
      flags:
        cflags: -march=native -mtune=native
        cxxflags: -march=native -mtune=native
      operating_system: centos8
      target: x86_64
      modules: []
      environment:
        set: # Needed for scotch
          BISON: bison
          FLEX: flex
      extra_rpaths: []

  #############
  # PACKAGES  #
  #############

  packages:
    all:
      target: [x86_64]
      compiler: [gcc]
      providers:
        blas: [intel-oneapi-mkl]
        lapack: [intel-oneapi-mkl]
        mpi: [hpcx-mpi]

    ####
    # make sure spack doesn't rebuild mpi, blas and lapack libs
    # without this it will try to build mpich and openblas
    mpi:
      buildable: false
    blas:
      buildable: false
    lapack:
      buildable: false

    ####
    # spec of packages to build

    # v0.6.2
    blt:
      require: "@git.9ff77344f0b2a6ee345e452bddd6bfd46cbbfa35=develop"
    # master - 10/18/24
    hypre:
      require: "@git.c893886d15eb57e87dd36efec23693ece3ddc88e"
    # v2024.07.0
    chai:
      require: "@git.df7741f1dbbdc5fff5f7d626151fdf1904e62b19=develop"
    # v2024.07.0
    umpire:
      require: "@git.abd729f40064175e999a83d11d6b073dac4c01d2=develop"
    # v2024.07.0
    raja:
      require: "@git.4d7fcba55ebc7cb972b7cc9f6778b48e43792ea1=develop"
    # v2024.07.0
    camp:
      require: "@git.0f07de4240c42e0b38a8d872a20440cb4b33d9f5=main"
    # v2.12.0
    caliper:
      require: "@git.287b7f3ad2d12f520aad04268d44f353cd05403c"
    # v0.9.2
    conduit:
      require: "@git.ad86e316ad56a75c099d30ca5ce75cff275b5924=develop"
    # master - 04/12/20
    uncrustify:
      require: "@git.401a4098bce9dcc47e024987403f2d59d9ba7bd2"
    # master - 04/26/20
    superlu-dist:
      require: "@git.0f6efc377df2440c235452d13d28d2c717f832a1"

    ####
    # spec of spack packages to reuse

    intel-oneapi-mkl:
      externals:
        - spec: intel-oneapi-mkl@2023.2.0 threads=openmp
          prefix: /opt/spack/opt/spack/linux-centos8-zen3/gcc-12.1.0/intel-oneapi-mkl-2023.2.0-os7byfaou43rtdoutsio7cqfta67uvpb
      buildable: False
    python:
      externals:
      - spec: python@3.11.7
        prefix: /opt/spack/opt/spack/linux-centos8-zen3/gcc-12.1.0/python-3.11.7-gtr54gwtvgrt7rcvecnjwbzo5mjvhlhr
      buildable: false
    cmake:
      externals:
      - spec: cmake@3.27.9
        prefix: /opt/spack/opt/spack/linux-centos8-zen3/gcc-12.1.0/cmake-3.27.9-qlycuifsyg46wiqljnglszevjl34seux
      buildable: false
    berkeley-db:
      externals:
      - spec: berkeley-db@18.1.40
        prefix: /opt/spack/opt/spack/linux-centos8-zen/gcc-8.5.0/berkeley-db-18.1.40-x4zdnigaawimrbhtaw3enreohi54ljwe
      buildable: false
    perl:
      externals:
      - spec: perl@5.38.0
        prefix: /opt/spack/opt/spack/linux-centos8-zen/gcc-8.5.0/perl-5.38.0-b7ny3twfj25hgukovwifhdbobv4zn3nw
      buildable: false
    mpfr:
      externals:
      - spec: mpfr@4.2.1
        prefix: /opt/spack/opt/spack/linux-centos8-zen/gcc-8.5.0/mpfr-4.2.1-6adatrj5k6lpmk4ozvmet7lwfdbibrca
      buildable: false
    gmp:
      externals:
      - spec: gmp@6.2.1
        prefix: /opt/spack/opt/spack/linux-centos8-zen/gcc-8.5.0/gmp-6.2.1-lflaucke4mt4xox245ahvqdehbr4k6i2
      buildable: false
    gcc-runtime:
      externals:
      - spec: gcc-runtime@12.2.1
        prefix: /opt/spack/opt/spack/linux-centos8-zen/gcc-12.1.0/gcc-runtime-12.1.0-dt4sq2ct65tsyhuv2f5l4r2sstfs7yuz
      buildable: false

    ####
    # spec of system packages to reuse

    # bin
    flex:
      externals:
      - spec: flex@2.6.1+lex
        prefix: /usr
      buildable: false
    git:
      externals:
      - spec: git@2.43.0
        prefix: /usr
      buildable: false
    gmake:
      externals:
      - spec: gmake@4.2.1
        prefix: /usr
      buildable: false
    m4:
      externals:
      - spec: m4@1.4.18
        prefix: /usr
      buildable: false
    # libs
    glibc:
      externals:
      - spec: glibc@2.28
        prefix: /usr
      buildable: false
    hpcx-mpi:
      externals:
      - spec: hpcx-mpi@2.20.0
        prefix: /sw/hpcx-v2.20-gcc-mlnx_ofed-redhat8-cuda12-x86_64/ompi
      buildable: false
    pkgconf:
      externals:
      - spec: pkgconf@3.0.0
        prefix: /usr
      buildable: false
    readline:
      buildable: false
      externals:
      - spec: readline@7.0
        prefix: /usr
    zlib:
      externals:
      - spec: zlib@1.2.11
        prefix: /usr
      buildable: false